"""The connector inventory, generated from the specs.

Which connectors exist, what they schedule and which credential each needs used
to be written down in six places by hand: two paragraphs of CLAUDE.md, two
READMEs, a Makefile comment and a skill. At two connectors, two of the six were
already wrong — they still named only Swoogo the day Customer.io landed.

So the facts are generated and the prose keeps only the mechanism. CI checks
this file is current, which makes a stale inventory a failed check rather than
something a reader has to notice.
"""

from __future__ import annotations

from pathlib import Path

from .spec import REPO_ROOT, load_all

DOCS_PATH = REPO_ROOT / "docs" / "sources.md"

HEADER = """<!-- Generated by `ingest inventory` — do not edit by hand. -->

# Connectors

What this checkout ingests, generated from `sources/*/source.yml`. A connector is
a directory: the spec is the contract, and its extension, fixtures, research
notes and reviewed schemas live beside it.

`status` is the whole scheduling story:

| status | what it means |
|---|---|
| `connected` | generates an unpaused ingest DAG on any stack that comes up, and needs its `token_env` set on every clone. Listed in `sources/CONNECTED`. |
| `paused` | DAGs exist and nothing ticks. For a credential mid-rotation. |
| `reference` | a worked example. Validated and built by the contract suite; scheduled by nothing. |
"""

FOOTER = """
## Adding one

`ingest scaffold <name>` writes the directory as `status: reference`; the
add-source skill fills it in. Flipping to `connected` and appending the name to
`sources/CONNECTED` is the deliberate last step, once the connector has been
proven to load.

See [`sources/CONTRACT.md`](../sources/CONTRACT.md) for what an `extension.py`
must supply, and [`sources/source.schema.json`](../sources/source.schema.json)
for the spec vocabulary.
"""


def _row(spec):
    schedule = spec.schedule or "—"
    tables = len(spec.resources)
    extras = []
    if spec.uses_extension:
        extras.append("extension")
    if spec.reconcile_schedule and spec.backfill_start:
        extras.append("reconcile")
    freshness = ", ".join(
        f"{entry['table']} ≤{entry.get('hours', 24)}h"
        for entry in spec.freshness_checks
    ) or "—"
    return (
        f"| `{spec.name}` | {spec.status} | `{schedule}` | {tables} | "
        f"`{spec.token_env}` | {freshness} | {spec.owner or '—'} | "
        f"{', '.join(extras) or '—'} |"
    )


def render():
    specs = sorted(load_all(), key=lambda s: (s.status != "connected", s.name))
    lines = [
        HEADER,
        "| connector | status | schedule | resources | credential | freshness SLO | owner | notes |",
        "|---|---|---|---|---|---|---|---|",
    ]
    lines.extend(_row(spec) for spec in specs)
    connected = [s for s in specs if s.is_connected]
    lines.append("")
    lines.append(
        f"{len(connected)} connected, {len(specs) - len(connected)} not scheduled."
    )
    lines.append(FOOTER)
    return "\n".join(lines)


def write(path=None):
    """Regenerate docs/sources.md. Returns (path, changed)."""
    target = Path(path) if path else DOCS_PATH
    text = render().rstrip() + "\n"
    changed = not target.is_file() or target.read_text() != text
    if changed:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text)
    return target, changed
