"""One enumeration of the connectors, for everything that is not Python.

Seven readers used to glob `sources/` independently: the spec loader, the DAG
generator, the pool-creation loop in compose, two greps in the deploy scripts,
the deploy's DAG-id prediction, and the tests. Three of them re-derived pool
names or orchestration defaults in their own dialect — one in an inline
`python -c`, two in `grep -oE`. They agreed by luck and by review.

Python still reads the specs directly; it owns the parser. Everything else —
shell, compose, terraform — reads this file, generated by that same parser. `jq`
is already a required host tool and is already in the Airflow image, so the
consumers get a format they can actually parse instead of a YAML dialect
approximated with a regular expression.

Committed rather than built on demand: terraform's `for_each` and the deploy's
verification both need it before anything in this repo has been installed. CI
regenerates and diffs it, so stale is a failed check rather than a silent
mismatch.
"""

from __future__ import annotations

import json
from pathlib import Path

from .spec import load_all, sources_dir

MANIFEST_FILENAME = "manifest.json"

# Bumped when the shape changes, so a consumer reading an older manifest fails
# loudly instead of finding a key missing.
VERSION = 1


def manifest_path(directory=None):
    base = Path(directory) if directory else sources_dir()
    return base / MANIFEST_FILENAME


def entry(spec):
    """What a non-Python consumer needs: enumeration and join keys, not the spec.

    Deliberately not the whole contract. A manifest that mirrored the spec would
    be a second copy of it, and the copy would be what people edited.
    """
    return {
        "name": spec.name,
        "status": spec.status,
        "path": f"{spec.name}/source.yml",
        "token_env": spec.token_env,
        "pool": spec.pool,
        "database": spec.dataset,
        "schedule": spec.schedule,
        "reconcile": spec.reconcile_schedule,
        "backfill_start": spec.backfill_start,
        "dag_ids": list(spec.dag_ids),
        "runtime": {task: spec.runtime_tier(task)
                    for task in ("ingest", "backfill", "reconcile")},
        "extension": spec.uses_extension,
        "resources": list(spec.resource_names),
        "owner": spec.owner,
    }


def build(directory=None):
    specs = load_all(directory)
    return {
        "version": VERSION,
        "sources": [entry(spec) for spec in sorted(specs, key=lambda s: s.name)],
    }


def load_manifest(directory=None):
    path = manifest_path(directory)
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError:
        return None


def write(directory=None):
    """Regenerate the manifest. Returns (path, changed)."""
    path = manifest_path(directory)
    payload = build(directory)
    # One source per block, sorted, with a trailing newline: two connector pull
    # requests then touch different lines and merge without a conflict.
    text = json.dumps(payload, indent=2, sort_keys=False) + "\n"
    changed = not path.is_file() or path.read_text() != text
    if changed:
        path.write_text(text)
    return path, changed
