-- Runs once, on first initialization of an empty warehouse volume.
--
-- ClickHouse has no schemas: a "schema" IS a database. Only one is created here,
-- and it is the one this repo owns outright:
--
--   ops   the pipeline's self-knowledge — quality verdicts and ingest runs.
--         `dq ops-init` owns the tables inside it and creates them on every run.
--
-- No raw_<source> database is created here, deliberately. This file runs once, on
-- an empty volume, so it could only ever know about the sources connected on the
-- day the host was built — and a source connected afterwards would never get one.
-- `ensure_database` in the ingest runtime creates raw_<source> before dlt connects
-- instead, which covers both cases with one mechanism. (It has to happen before
-- dlt connects at all: ClickHouse selects the database as part of connecting, so
-- dlt fails its pre-run sync with "Code: 81. Database raw_x does not exist" before
-- it could create anything itself.)
--
-- Nor is there an `analytics` database. Nothing in this repo writes one — the
-- stack lands raw sources and orchestrates them, and what the rows mean is decided
-- elsewhere. Whatever builds models can create its own container; an empty one
-- here would only advertise a layer that does not exist.

CREATE DATABASE IF NOT EXISTS ops;

-- No GRANTs here, deliberately. CLICKHOUSE_USER makes the entrypoint define the
-- user in users.xml, and that storage is read-only to SQL: any GRANT aborts the
-- whole init with "Code: 495 ... Cannot update user `warehouse` in users_xml
-- because this storage is readonly", leaving the container unhealthy forever.
-- The grants were also redundant — an XML-defined user already has full access,
-- verified against this image for every operation the stack performs: CREATE
-- DATABASE, CREATE/DROP TABLE and VIEW, INSERT, SELECT, ALTER, OPTIMIZE,
-- TRUNCATE, SHOW, and reading system.tables.
--
-- Splitting reader from writer is still the obvious hardening step, but it has
-- to be done in a users.d/*.xml file mounted into the server, not from here.
